name: Snake animation

on:
  schedule:
    - cron: "0 5 * * *" # se regenera todos los días a las 5:00 UTC
  workflow_dispatch: {} # también puedes lanzarla manualmente desde la pestaña Actions
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generar la serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: zharick-acosta
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg

      - name: Publicar en la rama "output"
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
